Repository simixsistemas/Simix.Ponto.Cloud.Docs, pull requests merged in 2024-06, with the labels that each got.

#2 Documentação Estabelecimentos.✨
  pt-BR/Cadastros/Estabelecimentos.md
Labels: enhancement

#4 Documentação Empresa ✨
  pt-BR/Cadastros/Empresa.md
Labels: documentation, enhancement

#3 Documentação coletores ✨
  pt-BR/Cadastros/Coletores.md
Labels: documentation, enhancement

#7 Documentação turnos especiais ✨
  pt-BR/Cadastros/TurnosEspeciais.md
Labels: documentation, enhancement

#5 Documentação Afastamentos ✨
  pt-BR/Cadastros/Afastamentos.md
Labels: documentation, enhancement

#11 Documentação configuração de banco de horas ✨
  pt-BR/Cadastros/BHConfig.md
Labels: documentation, enhancement

#10 Documentação Departamentos.✨
  pt-BR/Cadastros/Departamentos.md
Labels: documentation, enhancement

#9 Documentação Feriados ✨
  pt-BR/Cadastros/Feriados.md
Labels: documentation, enhancement

#8 Documentação Situações. ✨
  pt-BR/Cadastros/PontoSituacoes.md
Labels: documentation, enhancement

#6 Documento MobileConfigs. ✨
  pt-BR/Cadastros/MobileConfigs.md
Labels: documentation, enhancement

#16 Documentação regras prêmio✨
  pt-BR/Cadastros/RegrasPremio.md
Labels: documentation, enhancement

#15 Documentação Cargos ✨
  pt-BR/Cadastros/Cargos.md
Labels: documentation, enhancement

#13 Documentação cidades ✨
  pt-BR/Cadastros/Cidades.md
Labels: documentation, enhancement

#14 Documentação de cadastro do VTs ✨
  pt-BR/Cadastros/VTs.md
Labels: documentation, enhancement

#12 Documentação cadastro de seções ✨
  pt-BR/Cadastros/Secoes.md
Labels: documentation, enhancement

#19 Documentação Configurações ✨
  pt-BR/Cadastros/Config.md
Labels: documentation, enhancement

#18 Documentação de cadastro do VRs ✨
  pt-BR/Cadastros/VRs.md
Labels: documentation, enhancement

#22 Documentação PontoCalcTot. ✨
  pt-BR/Tabelas/PontoCalcTot.md
Labels: documentation, enhancement

#21 Documentação PontoCalcDia. ✨
  pt-BR/Tabelas/PontoCalcDia.md
Labels: documentation
